// <auto-generated />
namespace sys.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class After_commit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(After_commit));
        
        string IMigrationMetadata.Id
        {
            get { return "202505120440246_After_commit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
